### ISSUE TITLE
Is It Possible to Run RenderCV not From The CLI? 

### ISSUE THREAD

**Issue by alexwhb** [sinaatalay/RenderCV#104]
I'm wanting to pass in JSON or YAML into rendercv from a web service. Is this possible currently?

**Comment by sinaatalay** [comment]
Not at the moment, but we've got some plans in the works :) I will share the news with everyone soon.

**Comment by alexwhb** [comment]
Awesome! Excited for the announcement. 🎉

**Comment by sinaatalay** [comment]
Please see the announcement: https://github.com/sinaatalay/rendercv/discussions/160

RenderCV has a web app and a web API now.
