### ISSUE TITLE
Upgrade to fontawesome6

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#107]
Re: #91 and #101 

Upgrade to Version 6

https://docs.fontawesome.com/web/setup/upgrade

https://fontawesome.com/changelog/

**Comment by sinaatalay** [comment]
Thank you! `fontawesome6` doesn't exist in $\LaTeX$.

**Comment by TheColorDarkBlue** [comment]
> Thank you! `fontawesome6` doesn't exist in LATEX.

Is `fontawesome5` still supported? The last update seems to be from over 4 years ago.

<img width="539" alt="image" src="https://github.com/sinaatalay/rendercv/assets/146706527/66cc6192-f89c-4e26-9592-d11e7bdea2ad">

https://ctan.org/ctan-ann/pkg/fontawesome5

**Comment by sinaatalay** [comment]
Probably no one is working on it currently, but it works.

**Comment by mrexodia** [comment]
I found a package for `fontawesome6` here, seems to be fairly straightforward to integrate: https://github.com/CalaW/latex-fontawesome6. This would also make it possible to add X/Twitter as discussed in #109. Would you be open to using this package? If yes I can work on it and open a PR.

**Comment by sinaatalay** [comment]
Thank you for finding this @mrexodia. We should only do this only if Overleaf supports `fontawesome6`. A lot of our users take the generated $\LaTeX$ file and do the final touches in Overleaf.
