### ISSUE TITLE
Remove Twitter social network since it has been deprecated and renamed to X

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#109]
This rebrand is almost a year old. Twitter profiles automatically redirect from **twitter.com** to **x.com**. 

https://www.theverge.com/2024/5/17/23829098/twitter-x-com-url-links-switch

#101 #108 #107

**Comment by sinaatalay** [comment]
Thank you. Twitter has been removed from RenderCV in v1.11.
