### ISSUE TITLE
Suggestion: No more Page Breaks in Entries

### ISSUE THREAD

**Issue by Kigstn** [sinaatalay/RenderCV#115]
Hi! First of all thanks for creating this :)

I have one small suggestion: Currently, a single entry may be split onto two pages. I find this a bit annyoing and would rather want the entry to start on the second page, if there is not enough space on the first page.

![image](https://github.com/sinaatalay/rendercv/assets/38250010/1a7117f3-adfe-416d-b721-fcb9903e5a02)

**Comment by sinaatalay** [comment]
Thank you for the suggestion! The entries used to be nonbreakable, but we found that breaking them is better, especially for people with very long entries (see #47).

If you would like to achieve what you want, try updating your [`moderncv/ExperienceEntry.j2.tex`](https://docs.rendercv.com/reference/themes/moderncv/#experienceentry) (or other entries as well) from this:

```latex
\cventry{
    ((*- if design.show_only_years *))<<-entry.date_string_only_years->>((* else *))<<-entry.date_string->>((* endif -*))
}{\textbf{<<entry.company>>}}{
    <<-entry.position->>
}{
    <<-entry.location->>
}{}{}
((* for item in entry.highlights *))
\cvlistitem{<<item>>}
((* endfor *))
```

To this:

```latex
\begin{minipage}{\linewidth}
\cventry{
    ((*- if design.show_only_years *))<<-entry.date_string_only_years->>((* else *))<<-entry.date_string->>((* endif -*))
}{\textbf{<<entry.company>>}}{
    <<-entry.position->>
}{
    <<-entry.location->>
}{}{}
((* for item in entry.highlights *))
\cvlistitem{<<item>>}
((* endfor *))
\end{minipage}
```

The `moderncv` folder is created with `rendercv new "Your Name" --theme "moderncv"` command. See [here](https://docs.rendercv.com/user_guide/#getting-started-with-the-new-command) for details.

If it works, we should add this to the [FAQ](https://docs.rendercv.com/user_guide/faq/).

**Comment by Kigstn** [comment]
Yes that works!

Ideally, if a config option could be made for this, it would be the easiest IMO. If that is too much effort, I agree with adding the workaround to the FAQ - I don't think I am the only one with this "issue".

Thanks so much :)

**Comment by sinaatalay** [comment]
I'm currently not intending to include a configuration option because it would complicate the templates. However, if anyone has comments on this, please let me know.

**Comment by shawnz** [comment]
Any suggestions on how this could be achieved in the sb2nov theme? The minipage method doesn't seem to be compatible with the column system. Thanks, Shawn
