### ISSUE TITLE
rendercv/examples folder contents out of date 

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#119]
**Describe the bug**
* The PDF and YAML files are out of date and not sync-d up with new boilerplate content. See #118 and #120 
* The example PNG image files in the [README](https://github.com/sinaatalay/rendercv/blob/main/README.md) are also out of date
* The files were last edited 3 weeks ago

**Comment by sinaatalay** [comment]
Updating the `examples` folder is explained [here](https://docs.rendercv.com/developer_guide/writing_documentation/#updating-the-examples-folder). Each pull request that updates the sample content should also update the `examples` folder.
