### ISSUE TITLE
Add ability to build a cover letter.

### ISSUE THREAD

**Issue by achugr** [sinaatalay/RenderCV#12]
A cover letter is often a good addition to a CV.
A cover letter is more personalized, but there is a template that can be reused from letter to letter. Plus, it would be great if the CV and the cover letter are of the same formatting and style.
What do you think about the idea of adding the ability to generate a cover letter based on a template? I would be happy to describe my proposal in more detail if you think this functionality fits the project.

**Comment by sinaatalay** [comment]
Hello, and thank you for the suggestion!

I don't think incorporating cover letters into the current codebase would be a good idea, as it would require an entirely different code. I think the current code won't help with cover letters, as they are purely related to CVs. Therefore, I believe creating a separate package for cover letters would make more sense. A single codebase that does two independent things may not be practical to maintain.

I might be wrong (maybe for users, it's better to have them in the same package), and I would like to hear your view on this. How would you implement this, and how would it look from the user side?

**Comment by achugr** [comment]
Hello!
Overall I see the process this way: you have two YAML configs - one for CV (the base one) and one for cover letter (the base one). When you want to apply for a position, you create a new branch from the main. You put there a custom cover letter and maybe adjust your CV according to position requirements. If you find some adjustments good and generic enough, you bring them to the main branch.
This does not require it to be the same code base, this could be a separate project rendercoverletter 🙈. I think a cover letter from the implementation perspective is much simpler than a CV and in terms of the code, this can be a much smaller data model and a simple template file. Having it in one repo makes it easy to reuse the code and keep default template styles in sync.
Other than that, this could be a separate project for a cover letter and an umbrella project that makes it easy to use both and makes sure styles (fonts etc) are in sync.

**Comment by achugr** [comment]
I'll prepare a draft PR in a couple of days and we could discuss there if it fits.

**Comment by sinaatalay** [comment]
I will keep this issue until we come up with a way of handling cover letters. I agree with you; it's important to have this.

**Comment by sinaatalay** [comment]
I am moving this issue to Discussions.
