### ISSUE TITLE
North American Phone number format

### ISSUE THREAD

**Issue by prabhjotsbhatia-ca** [sinaatalay/RenderCV#130]
Please add support for North American Phone number format.
North American phone numbers are usually written in one of the following formats: 
(123) 234-5678
123-234-5678

Other less commonly used formats are: 
123 234 5678
123.234.5678

The format being mandated right now is +1-123-456-7890, which nobody would write in North America. 

In general too, the country code would be less likely to be written on a resume since one would usually have a local number in the geography they're applying for.

**Comment by sinaatalay** [comment]
Thank you.

I have added a new option to the data model: [`locale_catalog.phone_number_format`](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#locale_catalog-field)

It's set to `national` by default, which formats the phone number exactly how you would like. It looks at the country code and formats accordingly, using the Python port of Google's `libphonenumber`, [`phonenumbers`](https://github.com/daviddrysdale/python-phonenumbers).

**Comment by prabhjotsbhatia-ca** [comment]
Thank you. I tested it out and it looks great!

**Comment by sinaatalay** [comment]
The new functionality is released with `v1.13`.
