### ISSUE TITLE
Timespan shown in PDF even if not enabled in the theme config since v1.12

### ISSUE THREAD

**Issue by maxaudet** [sinaatalay/RenderCV#135]
**Describe the bug**
Starting with v1.12, the time span is added in the "Experience" section of the generated PDF, even if it's not enabled in the YAML.

- Before: Jan 2023 – present
- After: Jan 2023 – present 1 year 7 months

**To Reproduce**
Comment or remove the `show_timespan_in` field from the YAML file, then generate the CV and look at the "Experience" section dates in the generated PDF.

**Screenshots**
![image](https://github.com/user-attachments/assets/89b07219-5159-4981-8193-abc7b768cfaf)

**Comment by sinaatalay** [comment]
Thank you for opening an issue. I updated the default version to an empty list in `v1.12`. Do you think having the default value `["Experience"]` was better?

**Comment by maxaudet** [comment]
I'm not sure I understand why it's now displayed based on your comment, but on my end, I'd suggest not showing it unless it's enabled in the configuration.

**Comment by sinaatalay** [comment]
Oh, sorry, I thought you meant the opposite (not showing the timespan after v1.12)

Interestingly, the behavior is actually meant to be the opposite. Before v1.12, it should have shown time spans in the "Experience" section; after v1.12, the intention was not to show anything. I just tested it, and you're right. This is broken and not tested properly. I will fix it in the next release.

**Comment by sinaatalay** [comment]
This issue has been fixed in `v1.13`.
