### ISSUE TITLE
Add Patent Entry

### ISSUE THREAD

**Issue by RashKash103** [sinaatalay/RenderCV#136]
A new Patent Entry would be helpful. It would be similar to the Publication Entry but would have the following fields:
- Status (Pending or Approved)
- Year submitted/accepted
- Application/Patent number

**Comment by sinaatalay** [comment]
RenderCV's entry types are not data-oriented but rendering-oriented. We would only want to create a new entry type if we require a new rendering type.

You can showcase your patents with one of the seven [available entry types](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#cvsections-field). Maybe `NormalEntry` would be the best?

I am open to discussing any proposals for new rendering types if you have suggestions.
