### ISSUE TITLE
The `rendercv_output` dictionary mixed all cv files when I have several `yaml` cv files

### ISSUE THREAD

**Issue by Aithosa** [sinaatalay/RenderCV#145]
When I have multiple `yaml` cv files(such as my cv has different language ver), the output files are mixed in the `rendercv_output` folder.
```
.
├── Wang_Shuai_DU_CV.yaml # source file
├── Wang_Shuai_EN_CV.yaml # source file
└── rendercv_output
    ├── Wang_Shuai_CV.aux
    ├── Wang_Shuai_CV.html
    ├── Wang_Shuai_CV.log
    ├── Wang_Shuai_CV.md
    ├── Wang_Shuai_CV.pdf
    ├── Wang_Shuai_CV.tex
    ├── Wang_Shuai_CV_1.png
    ├── Wang_Shuai_CV_2.png
    ├── Wang_Shuai_DU_CV.aux
    ├── Wang_Shuai_DU_CV.html
    ├── Wang_Shuai_DU_CV.log
    ├── Wang_Shuai_DU_CV.md
    ├── Wang_Shuai_DU_CV.pdf
    ├── Wang_Shuai_DU_CV.tex
    ├── Wang_Shuai_DU_CV_1.png
    ├── Wang_Shuai_DU_CV_2.png
    └── __pycache__
        └── __init__.cpython-312.pyc
```

It could be better if output files can be classified by name like:
```
.
├── Wang_Shuai_DU_CV.yaml
├── Wang_Shuai_EN_CV.yaml
└── rendercv_output
    ├── Wang_Shuai_CV
    │   ├── Wang_Shuai_CV.aux
    │   ├── Wang_Shuai_CV.html
    │   ├── Wang_Shuai_CV.log
    │   ├── Wang_Shuai_CV.md
    │   ├── Wang_Shuai_CV.pdf
    │   ├── Wang_Shuai_CV.tex
    │   ├── Wang_Shuai_CV_1.png
    │   └── Wang_Shuai_CV_2.png
    ├── Wang_Shuai_DU_CV
    │   ├── Wang_Shuai_DU_CV.aux
    │   ├── Wang_Shuai_DU_CV.html
    │   ├── Wang_Shuai_DU_CV.log
    │   ├── Wang_Shuai_DU_CV.md
    │   ├── Wang_Shuai_DU_CV.pdf
    │   ├── Wang_Shuai_DU_CV.tex
    │   ├── Wang_Shuai_DU_CV_1.png
    │   └── Wang_Shuai_DU_CV_2.png
    └── __pycache__
        └── __init__.cpython-312.pyc
```

**Comment by sinaatalay** [comment]
Thank you for opening an issue. If we changed the `render` command’s `output_folder_name` option to `output_folder_path`, would it solve your issue (see [docs](https://docs.rendercv.com/user_guide/cli/#options-of-the-rendercv-render-command))? Also, in future releases, I plan to let users access the CLI options from the YAML file.

**Comment by Aithosa** [comment]
> Thank you for opening an issue. If we changed the `render` command’s `output_folder_name` option to `output_folder_path`, would it solve your issue (see [docs](https://docs.rendercv.com/user_guide/cli/#options-of-the-rendercv-render-command))? Also, in future releases, I plan to let users access the CLI options from the YAML file.

Thank you, adding command-line option can be helpful.
I was about to say I hate long option when using cli😂, but that's my problem.

**Comment by sinaatalay** [comment]
> I was about to say I hate long option when using cli😂, but that's my problem.

There is a short version 😃

```
rendercv render --output-folder-name FOLDER_NAME
```

is equivalent to

```
rendercv render -o FOLDER_NAME
```

**Comment by Aithosa** [comment]
Thanks🥰
