### ISSUE TITLE
Can I make PRs to add new social networks?

### ISSUE THREAD

**Issue by lisboamab** [sinaatalay/RenderCV#159]
A clear and concise description of what you want to add, improve, or fix in the documentation.

Can I create? I always use the lib to build designer CVs that include networks like Behance and Deviantart. Generally, as I use containers, I always have to modify ```curriculum_vitae.py```

PS: Sorry for creating the issue in this category, I didn't find a category about questions or things like that.

**Comment by sinaatalay** [comment]
Of course you can! That would be a very good contribution to RenderCV. The developer guide contains [a guide on how to add new social networks](https://docs.rendercv.com/developer_guide/faq/#how-can-i-add-a-new-social-network-to-rendercv). Please make sure to follow each step. It also describes how to add the tests for the added social networks. Thank you!
