### ISSUE TITLE
New rendercv app 🚀 

### ISSUE THREAD

**Issue by coolusaHD** [sinaatalay/RenderCV#171]
Hey @sinaatalay 
First of all - Love your package! 

I saw the new app and was wandering if you need/accept help from the community to build the app/web app.  I would love to contribute to the app, as my strengths are more in that field than in phyton packages.

Thanks ✌️

**Comment by sinaatalay** [comment]
Thank you!

Although the app's code is not open-source at the moment, if you want to contribute, please send an email to contact@rendercv.com. We can discuss the details. 

The tech stack is: Flutter + FastAPI.
