### ISSUE TITLE
`use_local_latex_command` not working in yaml file

### ISSUE THREAD

**Issue by jpgoldberg** [sinaatalay/RenderCV#178]
## Describe the bug

Attempting to set the command line option `--use-local-latex-command xelatex` within the `.yaml` source has no effect, and TinyTeX is used.

The option works correctly for me when given on the command line. And other render_option settings (such as `dont_generate_html`) work as expected.

### Documentation bug?

This may be a documentation bug, the documentation says

> Currently, it only includes the render_command field, which contains all the CLI options of the [rendercv render](https://docs.rendercv.com/user_guide/cli/#options-of-the-rendercv-render-command) command, as shown below.

I take "all the CLI options" to mean all. The "as shown below" appears to be an example of some such commands

## To Reproduce

Here are my modifications to the Example file. The modifications are all at the very top of the file

```yaml
rendercv_settings:
  render_command:
    use_local_latex_command: xelatex
    # use_local_latex_command: "xelatex"
    dont_generate_html: true
cv:
  name: John Doe
  location: Your Location
```

When I render that file, the TeX log file shows that pdflatex (via TinyTeX) has been used.

- I have attempted with both quoting xelatex and not quoting it.
- When I use `--use-local-latex-command xelatex` on the command line the log file tells me that XeLaTeX was used.
- I have confirmed that no html file is generated, thus showing that some of these render_command settings is working.

## Screenshots 

An excerpt from the TeX log file when `--use-local-latex-command xelatex` is _not_ given on the command line

```
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex 2024.5.1)  26 SEP 2024 14:54
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**/Users/jeffrey/src/github.com/jpgoldberg/jpg-cv/rendercv/rendercv_output/John
_Doe_Example_CV.tex

(/Users/jeffrey/src/github.com/jpgoldberg/jpg-cv/rendercv/rendercv_output/John_
Doe_Example_CV.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-03-14>

(/Users/jeffrey/.pyenv/versions/3.12.5/lib/python3.12/site-packages/rendercv/re
nderer/tinytex-release/TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
```

**Comment by sinaatalay** [comment]
Thank you. It will be fixed in the next release.
