### ISSUE TITLE
Cant render with some DOIs

### ISSUE THREAD

**Issue by SAADAT-Abu** [sinaatalay/RenderCV#184]
I am unable to render the .yml when I use this as the DOI of my publication "10.1007/978-3-319-69626-3_101-1" If I just remove the DOI the document renders perfectly. But this is the actual DOI of my paper and I need to put it.

Error looks like this:

`Welcome to RenderCV! Some useful links:                                    
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Title             ┃                                                Link ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ RenderCV App      │                                https://rendercv.com │
│ Documentation     │                           https://docs.rendercv.com │
│ Source code       │             https://github.com/sinaatalay/rendercv/ │
│ Bug reports       │      https://github.com/sinaatalay/rendercv/issues/ │
│ Feature requests  │      https://github.com/sinaatalay/rendercv/issues/ │
│ Discussions       │ https://github.com/sinaatalay/rendercv/discussions/ │
│ RenderCV Pipeline │    https://github.com/sinaatalay/rendercv-pipeline/ │
└───────────────────┴─────────────────────────────────────────────────────┘
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 0.0 s Validating the input file has finished.                                                                                                                                                                                              │
│ 0.1 s Generating the LaTeX file has finished.                                                                                                                                                                                              │
│ 0.3 s Rendering the LaTeX file to a PDF has started.                                                                                                                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
0.4 s ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ (2 out of 6 steps finished)

An error occurred:

RenderCV's built-in TinyTeX binaries couldn't render this LaTeX file into a PDF. This could be caused by one of two reasons:

1- The theme templates might have been updated in a way RenderCV's TinyTeX cannot render. RenderCV's TinyTeX is minified to keep the package size small. As a result, it doesn't function like a general-purpose LaTeX distribution.
2- Special characters, like Greek or Chinese letters, that are not compatible with the fonts used or RenderCV's TinyTeX might have been used.

However, this issue can be resolved by using your own LaTeX distribution instead of the built-in TinyTeX. This can be done with the '--use-local-latex-command' option, as shown below:

rendercv render --use-local-latex-command lualatex John_Doe_CV.yaml

If you ensure that the generated LaTeX file can be compiled by your local LaTeX distribution, RenderCV will work successfully. You can debug the generated LaTeX file in your LaTeX editor to resolve any bugs. Then, you can start using 
RenderCV with your local LaTeX distribution.

If you can't solve the problem, please open an issue on GitHub.
`
I tried "--use-local-latex-command" option too but it didn't worked.

I will be glad if if can be fixed.

Thanks a lot
A. Saadat

**Comment by sinaatalay** [comment]
Thank you for finding this! This issue has been fixed and it will be released soon.
