### ISSUE TITLE
Compiling non-English characters using --use-local-latex-command does not work

### ISSUE THREAD

**Issue by jaepil-choi** [sinaatalay/RenderCV#195]
I want to compile yaml that contains Korean character like 가. 

The instruction said that I need a local distribution of LaTeX instead of built-in TinyTex so I installed Tex Live for Windows. 

It seems I can use `xelatex` or `pdflatex` command to compile so I tried both of them like 

> rendercv render --use-local-latex-command xelatex Jaepil_Choi_CV.yaml

However, this gives the below result. 

I'm sure xelatex is installed and somehow tries to compile with it because the below command hangs for like 5 seconds and then gives the error. Before I installed Tex Live, the command would simply result in "xelatex not installed". 

How do I render non-English characters like 가 in rendercv? 

> 
> PS C:\Users\chlje\VSCodeProjects\auto-resume-pipeline\src> poetry run rendercv render --use-local-latex-command xelatex Jaepil_Choi_CV.yaml
> 
> Welcome to RenderCV! Some useful links:
> ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
> ┃ Title             ┃                                                Link ┃
> ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
> │ RenderCV App      │                                https://rendercv.com │
> │ Documentation     │                           https://docs.rendercv.com │
> │ Source code       │             https://github.com/sinaatalay/rendercv/ │
> │ Bug reports       │      https://github.com/sinaatalay/rendercv/issues/ │
> │ Feature requests  │      https://github.com/sinaatalay/rendercv/issues/ │
> │ Discussions       │ https://github.com/sinaatalay/rendercv/discussions/ │
> │ RenderCV Pipeline │    https://github.com/sinaatalay/rendercv-pipeline/ │
> └───────────────────┴─────────────────────────────────────────────────────┘
> ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │ 0.0 s Validating the input file has finished.                                                                        │
> │ 0.0 s Generating the LaTeX file has finished.                                                                        │
> │ 4.6 s Rendering the LaTeX file to a PDF has started.                                                                 │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> 4.7 s ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━ (2 out of 6 steps finished)
> 
> An error occurred:
> 
> RenderCV's built-in TinyTeX binaries couldn't render this LaTeX file into a PDF. This could be caused by one of two
> reasons:
> 
> 1- The theme templates might have been updated in a way RenderCV's TinyTeX cannot render. RenderCV's TinyTeX is minified
> to keep the package size small. As a result, it doesn't function like a general-purpose LaTeX distribution.
> 2- Special characters, like Greek or Chinese letters, that are not compatible with the fonts used or RenderCV's TinyTeX
> might have been used.
> 
> However, this issue can be resolved by using your own LaTeX distribution instead of the built-in TinyTeX. This can be
> done with the '--use-local-latex-command' option, as shown below:
> 
> rendercv render --use-local-latex-command lualatex John_Doe_CV.yaml
> 
> If you ensure that the generated LaTeX file can be compiled by your local LaTeX distribution, RenderCV will work
> successfully. You can debug the generated LaTeX file in your LaTeX editor to resolve any bugs. Then, you can start using
> RenderCV with your local LaTeX distribution.
> 
> If you can't solve the problem, please open an issue on GitHub.
> 

I also added needed package to compile Korean in Preamble.j2.tex file like below:

```
....
\usepackage{iftex} % check if engine is pdflatex, xetex or luatex

\usepackage{utf8} % for unicode characters
\usepackage{kotex} % for Korean language

% Ensure that generate pdf is machine readable/ATS parsable:
\ifPDFTeX
    \input{glyphtounicode}
   ....
```

Anything I should try more?

**Comment by sinaatalay** [comment]
RenderCV doesn't contain a general-purpose LaTeX distribution. It only contains a minimal subset of [TinyTeX](https://yihui.org/tinytex/) just to render our themes. So, if you want to use other capabilities of LaTeX, like writing in Korean, you will need to use your own LaTeX distribution with the [`--use-local-latex` option of the `rendercv render` command](https://docs.rendercv.com/user_guide/cli/#options-of-the-rendercv-render-command).

In order to use Korean, you will need to update your LaTeX file accordingly. But RenderCV cannot check if your LaTeX file is valid. It just tries to compile it with the distribution you provided, and if it can, it returns you the PDF. If it can't be compiled, there are some bugs in the LaTeX code, and they should be debugged using a LaTeX editor (like [Overleaf](https://www.overleaf.com/)), by trying to compile the generated LaTeX code manually.
