### ISSUE TITLE
Hash symbol in custom NormalEntry section

### ISSUE THREAD

**Issue by Vinhcognito** [sinaatalay/RenderCV#2]
**Describe the bug**
Unable to create a hash character in a custom NormalEntry block. Tried both:  `C#` and escaping it:  `C\#`

**To Reproduce**
```
  custom_sections:
    - title: Skillz
      entry_type: NormalEntry
      entries:
        - name: "Programming Languages:"
          highlights:
            - "C\#"
            - "Special characters test: üğç"
```

**Screenshots**
Console Output:
CRITICAL | ScannerError('while scanning a double-quoted scalar', <ruamel.yaml.error.FileMark object at 0x000002089ECD4380>, "found unknown escape character '#'"

![image](https://github.com/sinaatalay/rendercv/assets/48443988/2e998095-eba1-4c22-b2f3-d3a6cacb7d18)

**Comment by sinaatalay** [comment]
Thank you for finding this. In fact, I never coded something to escape special $\LaTeX$ characters. 08a4fcdcc09cacaff6fbbc20ea90187e1f2b6ad1 fixes the issue. Now, plain `C#` is fine. The new version of RenderCV with the fix will be online in ~20 minutes.
