### ISSUE TITLE
Add an official docker image to dockerhub?

### ISSUE THREAD

**Issue by MathiasVDA** [sinaatalay/RenderCV#215]
Hello,

I would like to use rendercv using a docker container so that I can integrate it in a gitlab ci/cd environment. But docker support could be interesting for people that don't want to install python on their computer.

Would you be open to have a dockerfile in this repository and a github action that publishes new versions to dockerhub? I can create a merge request if the answer is positive. Prerequisite: you need to have/create a docker account. The alternative would be that I create a repository myself that has the dockerfile and the github action and I trigger it when you create a new release.

Thank you!

**Comment by sinaatalay** [comment]
This sounds nice! It would be great if you could send a PR. I can create a Docker account.

**Comment by MathiasVDA** [comment]
Perfect, I'll try to find some time tomorrow
