### ISSUE TITLE
URL special characters are not properly escaped

### ISSUE THREAD

**Issue by MathiasVDA** [sinaatalay/RenderCV#223]
**Describe the bug**
When adding a markdown link like this:

`'[Link text](https://link.to.my.domain/#/pagename)'`

The rendering of the pdf will fail because the character # is not properly escaped. This also happens when the URL is encoded so that spaces are replaced with %20

**To Reproduce**
Add a markdown link with the character # or % to the yaml file

**Comment by bvahdat** [comment]
I also ran into the same problem and as a quick fix just escaped the hashtag through `\#`.

**Comment by MathiasVDA** [comment]
Yes, that's what I did as well after having to search for a bit. Then I created this issue so that it can be fixed and the next person will not have this issue

**Comment by sinaatalay** [comment]
Thank you. This issue has been fixed with v1.15.
