### ISSUE TITLE
Provide a setting parameter to keep all dates in ISO format (2020-01-01)

### ISSUE THREAD

**Issue by Aithosa** [sinaatalay/RenderCV#224]
What should I do if I want to keep dates in ISO format (2020-01-01). I don't want to convert them into human-friendly strings ("Jan 2020").

**Comment by sinaatalay** [comment]
This is possible. Please have a look at [`locale_catalog.date_style` field of the YAML file](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#locale_catalog-field).
