### ISSUE TITLE
Supports multi-level nested lists

### ISSUE THREAD

**Issue by Aithosa** [sinaatalay/RenderCV#226]
I wish to write my projects fields like this, but items in highlights can only be strings:
```markdown
    projects:
      - name: Multi-User Drawing Tool
        date: '[github.com/name/repo](https://github.com/sinaatalay/rendercv)'
        highlights:
          - Work 1
              - details 1
              - details 2
          - Work 2
              - details 1
              - details 2
          - 'Tools Used: C++, MFC'
```

Is there any solutions to make it?
- Support a more general section in which I could write things using little complex structure?
- make a special field support multi-level nested lists(so i can use it to replace highlights)?

**Comment by sinaatalay** [comment]
Yes, this is discussed in #177.
