### ISSUE TITLE
Allow future end dates

### ISSUE THREAD

**Issue by Vinhcognito** [sinaatalay/RenderCV#25]
There should be a way to allow future education end dates or a way to force render despite the error.

![image](https://github.com/sinaatalay/rendercv/assets/48443988/ea5ab0a9-61ec-4842-8252-6476d5e2b134)

**Comment by sinaatalay** [comment]
Thank you! You're right; this is too strict. I will update this in the next release.

**Comment by lhegstrom** [comment]
In the publications section this is definitely something that would be awesome as well. Being able to list abstract / paper / presentations that are accepted for a conference in a few months, for example

**Comment by sinaatalay** [comment]
That’s a good point as well.

I already pushed the change. It won’t check if the dates are in the future (for all the entry types) in the next release. I will close this issue after the release.
