### ISSUE TITLE
KeyError: 'design' on fresh installation with pipx

### ISSUE THREAD

**Issue by ViggieM** [sinaatalay/RenderCV#250]
**Describe the bug**
`rendercv render `2024_CV.yaml` throws an exception `KeyError: 'design'` on a fresh installation.

**To Reproduce**

1. Install rendercv with pipx: `pipx install rendercv`
2. Create a new cv with `rendercv new 2024`
3. Render the new cv with `rendercv render 2024_CV.yaml`

At this point I get the KeyError

**Screenshots**
![image](https://github.com/user-attachments/assets/e0ad97a5-4e83-445e-bcde-df02e566b171)

**Comment by sinaatalay** [comment]
Thank you. Yes, we will fix this as soon as possible. It happens in Python 3.10 and 3.11. We had an error in our pipeline, RenderCV v1.15 was only tested with Python 3.13 by mistake.

**Comment by sinaatalay** [comment]
This issue has been fixed in v1.16.

**Comment by ViggieM** [comment]
Works now, thank you!
