### ISSUE TITLE
docs: Add link to docs from rendercv.com

### ISSUE THREAD

**Issue by tobybaratta** [sinaatalay/RenderCV#253]
Hi!

It would be great to be able to get to the docs page easily from `rendercv.com`, maybe in the left nav (since there aren't blog posts right now)? 

I only found the documentation through clicking around in the editor UI (and honestly not even sure how I got to it, sorry!).

It'd be great for people just looking at the project's site, rather than coming from GitHub.

**Comment by sinaatalay** [comment]
Thanks. We added it: [rendercv.com](https://rendercv.com)
