### ISSUE TITLE
Add awards / conferences section type

### ISSUE THREAD

**Issue by tobybaratta** [sinaatalay/RenderCV#255]
It would be great to be able to have a section that would be clearly identified as Awards / Certifications or other one-line sections that should be grouped together. Or, a way of having different _types_ of bullets (and using them in conjunction with each other). This would potentially be just having a group of One Line entries?

The best way that I've found to mimic this is just putting "-name" under projects?

**Comment by sinaatalay** [comment]
Thank you. You mean entry type, right? Could you please share a picture of how this entry type would look in a PDF? If the desired appearance can be achieved using one of the [seven built-in entry types](https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/#cvsections-field) (for example, by using only the `name` field in `NormalEntry` you mentioned), then we wouldn't need to create a new entry type. The philosophy behind the entry types is based on visual representation, not content. Therefore, we don't need a new entry type for each data type; instead, we only need one for each visual type.

**Comment by sinaatalay** [comment]
Feel free to comment under the issue, I am closing it for now.
