### ISSUE TITLE
Locale Catalog is not used

### ISSUE THREAD

**Issue by Suuniil** [sinaatalay/RenderCV#275]
1. The bug
Using a locale catalog simply does not work. To reproduce, simply use the example catalog from the documentation: https://docs.rendercv.com/user_guide/structure_of_the_yaml_input_file/ on any file, and you will see that changing any of the settings does not have any effect.

2. The fix, and its issue
I have already fixed this for myself locally; however, my fix makes tests fail, so I believe something there is still wrong (which is why I am not giving a PR directly). The method "update_locale_catalog" in rendercv_data_model.py returns LocaleCatalog(), which is a defaulted instance of the locale catalog, thus resetting it. Changing the validation function to instead have locale_catalog as second input argument, and then returning that, fixes the issue. 
```
    @pydantic.field_validator("locale_catalog")
    @classmethod
    def update_locale_catalog(cls, locale_catalog: LocaleCatalog) -> LocaleCatalog:
        """Update the output folder name in the RenderCV settings."""
        # Somehow, we need this for `test_if_local_catalog_resets` to pass.
        return locale_catalog
```
This however makes the exact test fail that this function seems to have been supposed to fix.

As a sidenote, the schema.json for VS-code editing of the yaml file seems to not be up to date with the changes in 1.17, the move of the two options into locale_catalog has not been added into that schema.json yet.

**Comment by sinaatalay** [comment]
Thanks. It is fixed with v1.18.
