### ISSUE TITLE
seperator_between_connections is misspelled

### ISSUE THREAD

**Issue by miguelandres** [sinaatalay/RenderCV#277]
Should be separator_between_connections. It may be hard to switch between one and the other so I would understand if this were prioritized very low or not done at all

**Comment by sinaatalay** [comment]
Thank you, I just realized this a week ago. It will be fixed with #271.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Corrected the spelling of 'seperator_between_connections' to 'separator_between_connections' in the Header.j2.tex files for classic, engineeringresumes, and sb2nov themes.

You can review changes in this commit: https://github.com/mark-addams001881/rendercv-rendercv-277/commit/b213b6352044dd5efa7c96a02e43030b44b79485.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sinaatalay** [comment]
This is fixed with v1.18.
