### ISSUE TITLE
Making DOI optional for publications

### ISSUE THREAD

**Issue by fernandocamargoai** [sinaatalay/RenderCV#33]
I have a paper that was published in a workshop on NeurIPS and it doesn't seem like a DOI was generated for it. I tried to add it without the DOI, but it seems that DOI is currently required. Could this field be optional?

**Comment by lhegstrom** [comment]
Additionally, the field should probably have an opt in to verify the doi:

https://github.com/sinaatalay/rendercv/blob/5f0ca8b40611ddee27c4bd5dd05e13c535915f1e/rendercv/data_models.py#L514-L530

As of now, this slows down the rendering from nearly instant to quite a long time if you have a lot of entries.

**Comment by fernandocamargoai** [comment]
> Additionally, the field should probably have an opt in to verify the doi:
> 
> https://github.com/sinaatalay/rendercv/blob/5f0ca8b40611ddee27c4bd5dd05e13c535915f1e/rendercv/data_models.py#L514-L530
> 
> As of now, this slows down the rendering from nearly instant to quite a long time if you have a lot of entries.

Oh, so that's why my CV started taking so long to render.

**Comment by sinaatalay** [comment]
Unfortunately, optionally disabling DOI validation is not very straightforward. I won't be able to implement that. Could you please let me know how long does it take to validate? CLI shows it. I might think of disabling DOI validation for good.

In the next release, DOI won't be a required field.
