### ISSUE TITLE
Allow disabling word wrapping

### ISSUE THREAD

**Issue by fernandocamargoai** [sinaatalay/RenderCV#34]
When using `text_alignment: justified`, we get some word wrapping, which might confuse ATS systems. Using `text_alignment: left-aligned` avoids that, but looks worse. We would benefit from having the option to turn off work wrapping.

**Comment by samueloph** [comment]
I'm not experienced with latex but I've managed to disable word-wrapping with
```
\hyphenpenalty 10000 % Never hyphenate a word
\exhyphenpenalty 10000 % Never hyphenate a word
```

I have no idea how good of a workaround this is, of if there are side effects, but so far it worked.

**Comment by sinaatalay** [comment]
Thank you for opening the issue! This option is only available in `classic` and `sb2nov` themes. I added one more option: `justified-with-no-hyphenation`. I will release it with v1.6 soon.
