### ISSUE TITLE
Make RenderCV PDFs parsable by applicant tracking software

### ISSUE THREAD

**Issue by sinaatalay** [sinaatalay/RenderCV#41]
_Originally posted by @fernandocamargoai in https://github.com/sinaatalay/rendercv/discussions/32#discussioncomment-8687923_

**Comment by ferdavs** [comment]
One additional way to test this is to apply for Google Jobs :)
Google's tool fails to extract

**Comment by sinaatalay** [comment]
We did some tests, and RenderCV CVs are parsable by ATS. We plan to discuss this in a blog post soon: [rendercv.com ](https://rendercv.com)

**Comment by TheColorDarkBlue** [comment]
Check this out @sinaatalay https://www.open-resume.com/resume-parser
