### ISSUE TITLE
Allow work experience highlights to be broken in multiple pages

### ISSUE THREAD

**Issue by samueloph** [sinaatalay/RenderCV#47]
I don't know if this affects all themes, but I've noticed that with the classic one, having too many highlights under the "Experience" section will result in weird formatting of the pages, since the template will not allow for the highlights to be split between pages.

I did some searches and found results that might allow me fix this, but I haven't managed to do it yet, example:
https://tex.stackexchange.com/questions/165793/how-to-make-a-table-on-more-than-one-page-by-using-the-table-environment

**Comment by sinaatalay** [comment]
Thank you! It’s a critical point. I will fix this in my first availability.

**Comment by sinaatalay** [comment]
I released the fix with version 1.7.
