### ISSUE TITLE
rendercv version 1.5 breaks Experience section

### ISSUE THREAD

**Issue by AndreasKarasenko** [sinaatalay/RenderCV#49]
**Describe the bug**
Version 1.5 breaks the rendering of "company" and "position" in the experience section.

**To Reproduce**
- Install rendercv==1.5
- create new cv with default yaml `rendercv new test`
- render the pdf `rendercv render test_CV.yaml`

**Screenshots**
Default cv under 1.5
![grafik](https://github.com/sinaatalay/rendercv/assets/52670382/aa36843c-3b9a-4af7-8e42-4fa2b04ab2cc)

Default cv under 1.4
![grafik](https://github.com/sinaatalay/rendercv/assets/52670382/e5abed4b-d2dc-4c6a-8d8c-2097fe7107f2)

**Comment by 0x4ym4n** [comment]
I'm here to open the same issue.

**Comment by sinaatalay** [comment]
This will be fixed in ~2 hours with version 1.6. Thank you!
