### ISSUE TITLE
Undefined control sequence with \pdfglyphtounicode (lualatex)

### ISSUE THREAD

**Issue by c2tz** [sinaatalay/RenderCV#52]
**Describe the bug**
when I use lualatex (not tested but probably the same as xelatex so should only work with pdflatex) the last two lines of the "Preamble.j2.tex" file crash the compilation. However, when I override the file and delete these two lines, it works.

**To Reproduce**
1. run : `rendercv render --use-local-latex-command lualatex .\John_Doe_CV.yaml`

**Screenshots**
Log here :
[John_Doe_CV.log](https://github.com/sinaatalay/rendercv/files/14844530/John_Doe_CV.log)

**Comment by sinaatalay** [comment]
This issue should be fixed with version 1.7. Could you please confirm if it has been fixed? Thank you.

**Comment by c2tz** [comment]
Hello, no it doesn't seem to correct here are the logs I have, it's the same thing. I'll see about creating a test repo and sharing it (by tomorrow).

[John_Doe_CV_2.log](https://github.com/sinaatalay/rendercv/files/14911044/John_Doe_CV.log)

**Comment by c2tz** [comment]
@sinaatalay You are on the repo : https://github.com/c2tz/lualatex-rendercv

**Comment by sinaatalay** [comment]
This issue has been fixed in version `1.8`.
