### ISSUE TITLE
Generate a png in addition to the pdf and markdown files

### ISSUE THREAD

**Issue by c2tz** [sinaatalay/RenderCV#57]
### Discussed in https://github.com/sinaatalay/rendercv/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **c2tz** April 25, 2024</sup>
Let me explain, I'd like rendercv to be able to generate a png in addition to the pdf and md files. I found this [example](https://github.com/GiovanniMenzano/cv) and it seems like a good idea because you could have a preview without having to download the pdf from a readme file on github. Does this sound feasible ?</div>

**Comment by sinaatalay** [comment]
This issue should have been fixed with v1.9. Please comment if you encounter any problems.
