### ISSUE TITLE
Change the name of the output folder and the path of the files in it

### ISSUE THREAD

**Issue by c2tz** [sinaatalay/RenderCV#58]
### Discussed in https://github.com/sinaatalay/rendercv/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **c2tz** April 25, 2024</sup>
I would like to change the name of the `rendercv_output` folder to just "output". What should I do?

Can I also change the output path of the files, for example I'd like to have only the pdf directly in the root of my repo rather than in this `rendercv_output` folder (I know what I'm asking is possible with github-actions but directly from rendercv).</div>

**Comment by sinaatalay** [comment]
This issue should have been fixed with v1.9. Please comment if you encounter any problems.
