### ISSUE TITLE
Greek letters cannot be rendered

### ISSUE THREAD

**Issue by LabAsim** [sinaatalay/RenderCV#63]
In its current state, rendercv cannot render greek letters. 

I found a way to manually overcome this problem.

1. Use manually `lualatex` instead of `pdflatex` in `renderer.py` (lines 942-946)
2. Insert these lines in Preamble.j2.tex of the theme that you use (for example `themes/classic/Preamble.j2.tex`) 
`\usepackage{fontspec}`
`\setmainfont{Times New Roman}` 
and remove the default `\usepackage[default, type1]{sourcesanspro} % for using source sans 3 font`

In this way, Greek & English letters are rendered just fine!

My setup:

- Windows 10
- Python 3.11
- Rendercv 1.8

I hope that this post is helpful to anyone stuck on the same problem!

**Comment by sinaatalay** [comment]
I am closing this issue since it's now connected with #73. Thank you!
