### ISSUE TITLE
Fix errors related to emails with special characters

### ISSUE THREAD

**Issue by 0x4ym4n** [sinaatalay/RenderCV#64]
I noticed when there is an underscore "_" within the email id, the rendercv utlity compiles the yaml file successfully, however when the tex is being compiled to PDF file it will start complaining from syntax issues, see below:

*geometry* detected driver: pdftex
(phath_to/TinyTeX/texmf-dist/tex/latex/fontawesome5/ufontawesomefree1.fd)
! Missing $ inserted.
<inserted text>
                $
l.153 ...ace*{0.13cm}some_one_error_prone_email@hotmail.com}}

**Comment by sinaatalay** [comment]
Thank you! This issue will be fixed with the next release (version 1.9). I will comment on this issue and close it once it's released.

**Comment by sinaatalay** [comment]
This issue should have been fixed with v1.9. Please comment if you encounter any problems.

**Comment by ASBioinfo** [comment]
Hi,
I still got the rendering error for "_" in email ID, Using the latest version of rendercv

**Comment by sinaatalay** [comment]
That’s strange because I added it to the tests. Could you please share the error message?

**Comment by ASBioinfo** [comment]
Thank you for a quick reply,

**Input in yaml file**
`- bullet: "**Mr. faiz Alam**, [faiz_alam@gmail.com](mailto:faiz_alam@gmail.com)"`

**error message**
![Screenshot from 2024-06-24 04-16-54](https://github.com/sinaatalay/rendercv/assets/76941752/ef3c518d-8f2b-4c40-9acf-03d4c799b7ba)
