### ISSUE TITLE
ImportError: attempted relative import with no known parent package when attempting to use the custom theme

### ISSUE THREAD

**Issue by zinzli** [sinaatalay/RenderCV#68]
Getting this error whenever I attempt to use the engineering resumes theme. It was not included in the installation of the RenderCV utility, so I tried to insert it manually wherever it was missing in the source files. I can't figure out why the path file is not being found.

![Screenshot 2024-05-18 at 00 35 35](https://github.com/sinaatalay/rendercv/assets/43334176/5769a941-58ca-45c2-b19d-6f0ac2a99a78)

![Screenshot 2024-05-18 at 00 34 44](https://github.com/sinaatalay/rendercv/assets/43334176/4a015df7-33ac-40b8-bc87-757365a6fbdf)

**Comment by sinaatalay** [comment]
That two dots should be replaced with `rendercv.themes`. I will have a look when I'm available. RenderCV v1.8 should work as well.
