### ISSUE TITLE
Answer an FAQ: Can I add a profile picture?

### ISSUE THREAD

**Issue by sinaatalay** [sinaatalay/RenderCV#74]
I have added a FAQ section to the user guide. Your assistance with this is greatly appreciated.

**Comment by edavalosanaya** [comment]
This feature would be great!

**Comment by kito323** [comment]
Using `moderncv` theme it is actually quite easy. After first generation you have the `moderncv/Preamble.j2.tex` file. In this you can follow any moderncv LaTeX code basically and they have a `\photo` command:
> \photo A command for a photo. Takes the image file name as a required argument. Takes the
height of the photo and the thickness of the photo frame as optional arguments.
`\photo[<photo height >][< frame thickness >]{<photo file name >}`

Keep in mind that the root directory for the .tex file will be `rendercv_output` folder. So for example, if you want to keep your photo in the folder with `Your_Name_CV.yaml` then you should add something like this:
`\photo[3cm][1pt]{../YourPhoto.jpg}`

See more about moderncv documentation [here](https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/moderncv/manual/moderncv_userguide.pdf).

_Note: As this solution only caters `moderncv` theme and I have no idea about other themes then I don't think it's worthy of pull request. Maybe it is, let me know. I just thought it might be good info for some._

**Comment by sinaatalay** [comment]
@kito323 Thank you! All the files inside the theme folder (`moderncv`) will be automatically copied to `rendercv_output` folder. So, putting the photo inside the `moderncv` folder is an option too.

If you would like to contribute the documentation, you can send a pull request to update [the FAQ page](https://docs.rendercv.com/user_guide/faq/). If you're interested, see the [developer guide](https://docs.rendercv.com/developer_guide/). We can update the answer for the other themes later.

**Comment by sinaatalay** [comment]
Profile pictures will be supported in the next release, thanks to #193.
