### ISSUE TITLE
Remove 3rd party dependencies as source

### ISSUE THREAD

**Issue by michael-sbarra** [sinaatalay/RenderCV#8]
This project can minimize its footprint by removing the following 3rd party dependencies from source and instead pull them in in the install/setup stage:

Tools:
    1. [ ] TinyTex
Fonts:
    1. [ ] Source-sans
    1. [ ] Roboto
    1. [ ] EB-Garmand

**Comment by sinaatalay** [comment]
This is a very good point. It would be great to achieve this eventually. I will keep this open until we find a way.

A potential issue that may arise when making TinyTeX a dependency:

- I made TinyTeX smaller (~500 MB to ~100 MB). Even though we can make it a dependency and let users install it during RenderCV installation, we wouldn't want them to install the whole 500 MB package.

I'm not knowledgeable enough about adding the fonts to dependencies. But I'm sure there is an elegant way.

**Comment by michael-sbarra** [comment]
> This is a very good point. It would be great to achieve this eventually. I will keep this open until we find a way.
> 
> A potential issue that may arise when making TinyTeX a dependency:
> 
>     * I made TinyTeX smaller (~500 MB to ~100 MB). Even though we can make it a dependency and let users install it during RenderCV installation, we wouldn't want them to install the whole 500 MB package.
> 
> 
> I'm not knowledgeable enough about adding the fonts to dependencies. But I'm sure there is an elegant way.

@sinaatalay Which version of TinyText did you start with to make smaller? They offer four different bundles: https://github.com/rstudio/tinytex-releases#releases. I experimented and discovered that the regular `TinyTeX` bundle (~200MB archive) has all the dependencies this project needs (`titlesec` and `enumitem`) in addition to the ones in `TinyTeX-1`.

**Comment by sinaatalay** [comment]
@michael-sbarra I used regular TinyTeX. Yes, it has everything we need and more. Its compressed version is 225 MB, but it should be around ~500 MB after the extraction.

**Comment by michael-sbarra** [comment]
@sinaatalay I think its great that you are cognizant of the size of external dependencies that your project depends on. However, it is not a best practice to manually download dependencies, strip away the pieces a project doesn't need, and then include that dependency in the distribution of a project. 

The `TinyTex-1` bundle can be used, then only the extra packages can be installed instead of all of them from `TinyTex`:
```shell
tlmgr install titlesec enumitem fontawesome5 eso-pic bookmark lastpage
 ```

**Comment by sinaatalay** [comment]
@michael-sbarra Okay, that sounds really nice. How can we achieve this during installation, though? I have never added a non-Python dependency to a Python project before.

**Comment by michael-sbarra** [comment]
@sinaatalay Great question! Apparently as of today, this functionality doesn't exist. There is a PEP proposal for it: https://peps.python.org/pep-0725. I think the next best option is to just list the installation steps in the README. I have it tested for just `TinyTex` on macOS, I can't test the Windows one. #9

**Comment by sinaatalay** [comment]
I am closing this issue because, in v1, TinyTeX has been moved to [another repository](https://github.com/sinaatalay/tinytex-release), which is being pulled as a submodule.
