### ISSUE TITLE
Include release date to output of `rendercv --version` CLI command

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#82]
For example: `RenderCV v1.10 2024-05-26`

**Comment by sinaatalay** [comment]
I have never seen this in other software, and it requires us to keep the track of release date in the source code. Would this be helpful? If there isn't any obvious help, I would omit this enhancement.

**Comment by TheColorDarkBlue** [comment]
Alternatively, is there a way to tell the user that their version is out of date? This was just an idea that came to mind because I had no idea if the version I was on was the latest. Unlike other software, there's no "Check for updates" button or equivalent.
