### ISSUE TITLE
[DEV] no matches found: .[docs,tests,dev] error

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#84]
**Describe the bug**

> Python 3.12.3 installed
> pip 24.0 installed
> macOS Sonoma 14.5

> Developer Guide -> [Getting Started section](https://docs.rendercv.com/developer_guide/#getting-started) -> **Step 6. Install the dependencies.**: 

After entering `pip install --editable .[docs,tests,dev]`,

I received this error message: `zsh: no matches found: .[docs,tests,dev]`

**To Reproduce**

`git clone --recursive https://github.com/sinaatalay/rendercv.git`
`cd rendercv`
`python -m venv .venv`
`source .venv/bin/activate`
`pip install --editable .[docs,tests,dev]`

**Screenshots**

<img width="953" alt="image" src="https://github.com/sinaatalay/rendercv/assets/146706527/2aef4c06-a52b-448a-91f5-9c059ae05b56">

**Comment by sinaatalay** [comment]
Are you sure that your current working directory (check with `pwd`) is the repository's root?

**Comment by TheColorDarkBlue** [comment]
> Are you sure that your current working directory (check with `pwd`) is the repository's root?

Yes. Were you able to reproduce the bug?

**Comment by sinaatalay** [comment]
Could you try `pip install --editable ".[docs,tests,dev]"`?

**Comment by TheColorDarkBlue** [comment]
> pip install ".[docs,tests,dev]"

Here's the output.

![Screenshot 2024-06-11 at 12 08 48 PM](https://github.com/sinaatalay/rendercv/assets/146706527/bfcd164a-04bd-4623-9095-637530d39160)

**Comment by sinaatalay** [comment]
Did it work?

**Comment by TheColorDarkBlue** [comment]
> Did it work?

Define what you mean by "work". This is the final step in the [Developer Guide's Getting Started section] and I'm unsure of how to test whether or not it "worked".

**Comment by sinaatalay** [comment]
It works if it says "Successfully installed" and then lists a bunch of packages with their versions.

**Comment by TheColorDarkBlue** [comment]
> It works if it says "Successfully installed" and then lists a bunch of packages with their versions.

It seems to have worked. Did you test this on your end as well?

**Comment by sinaatalay** [comment]
Okay, thank you! I will update the documentation.
