### ISSUE TITLE
Add Google Scholar social network

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#85]
Google Scholar is a very prevalent social network, especially for researchers. I believe it is more commonly found on resumes and CVs than ResearchGate and ORCID.

**Comment by sinaatalay** [comment]
I have thought about this, but I haven't added it because Google Scholar's usernames don't look good at all. But I agree, we can add this.

**Comment by TheColorDarkBlue** [comment]
Yeah Google Scholar usernames being just random numbers isn't too clean, though in my experience, it's much more commonly found on resumes and CVs than ResearchGate or ORCID.
