### ISSUE TITLE
Add way to notify user that there is a new version of RenderCV available

### ISSUE THREAD

**Issue by TheColorDarkBlue** [sinaatalay/RenderCV#89]
Continuing discussion from [Issue #82](https://github.com/sinaatalay/rendercv/issues/82), could users be notified if their version of RenderCV is out of date? Also requesting for a way to view version history and the change log!

For example, this button for BetterDisplay opens up this page [https://waydabber.github.io/BetterDisplay/changelog.html?tag=v2.3.4
](https://waydabber.github.io/BetterDisplay/changelog.html?tag=v2.3.4)
<img width="257" alt="image" src="https://github.com/sinaatalay/rendercv/assets/146706527/0d426663-f0a0-45a2-943b-c511c7dd743e">

**Comment by sinaatalay** [comment]
Thank you! This will be available in the next release.
