### ISSUE TITLE
Relative path does not work

### ISSUE THREAD

**Issue by sahiljhawar** [sinaatalay/RenderCV#95]
**Describe the bug**
When I use relative path it says file doesn't exists.

**To Reproduce**
```bash
git clone --recursive https://github.com/sinaatalay/rendercv.git
cd rendercv
rendercv render examples/John_Doe_Sb2novTheme_CV.yaml
```

**Screenshots**
<img width="932" alt="image" src="https://github.com/sinaatalay/rendercv/assets/55475299/c4f6bd03-6d15-4d18-8577-14c746a8ec45">

**Comment by sinaatalay** [comment]
Thank you! This will be fixed in the next release.
