### ISSUE TITLE
Local installation does not work

### ISSUE THREAD

**Issue by sahiljhawar** [sinaatalay/RenderCV#98]
**Describe the bug**
Local installation does not work. I am using the default yaml as generated by `rendercv new`

**To Reproduce**
```bash
pip install .
```

**Screenshots**
<img width="1324" alt="image" src="https://github.com/sinaatalay/rendercv/assets/55475299/8794caf3-3cba-4be9-afd1-4f828b345bff">

even with the `--use-local-latex-command pdflatex` it does not work.

<img width="1330" alt="image" src="https://github.com/sinaatalay/rendercv/assets/55475299/be47f88f-cde3-4ab9-ad2e-318a4f879803">

**Comment by sinaatalay** [comment]
Do you get an error message?

**Comment by sinaatalay** [comment]
Because the repository needs to be cloned recursively. Please see the developer guide (users should install rendercv from pip).

**Comment by sahiljhawar** [comment]
yes, I cloned the repo recursivley

**Comment by sahiljhawar** [comment]
Okay, so I removed the tiny-latex and cloned it seperately in the same dir
